[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"

[dev]
  command = "npm run start"
  publish = "dist"

# Proxy Cloudinary
[[redirects]]
  from = "/cloudinary/*"
  to = "https://res.cloudinary.com/wolstenh/:splat"
  status = 200

# Proxy Lambda functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "https://cranky-mcnulty-01683e.netlify.app"
  to = "https://wolstenhol.me"
  status = 301
  force = true

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*.no-css.html"
  [headers.values]
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/*.no-js.html"
  [headers.values]
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/*.no-css"
  [headers.values]
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/*.no-js"
  [headers.values]
    X-Robots-Tag = "noindex"

# Redirect to custom 404
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404