[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"
  ignore = "git log -1 --pretty=%B | grep test:"

[dev]
  command = "npm run start"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/proxy/cloudinary/*"
  to = "https://res.cloudinary.com/wolstenh/:splat"
  status = 200

[[redirects]]
  from = "/proxy/jsdelivr/*"
  to = "https://cdn.jsdelivr.net/:splat"
  status = 200

[[redirects]]
  from = "/proxy/gstatic/*"
  to = "https://t2.gstatic.com/:splat"
  status = 200

[[redirects]]
  from = "/api/recently-played"
  to = "https://eoh55mp2n2usj4p.m.pipedream.net"
  status = 200

[[redirects]]
  from = "/api/recently-played-spotify"
  to = "https://eoh55mp2n2usj4p.m.pipedream.net"
  status = 200

# Proxy Lambda functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "https://cranky-mcnulty-01683e.netlify.app/*"
  to = "https://wolstenhol.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://wolstenhol.me/no-js"
  to = "https://wolstenhol.me/?no-js"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = '''
      public,
      max-age=31536000,
      immutable'''

[[headers]]
  for = "/favicon/*"
  [headers.values]
    Cache-Control = '''
      public,
      max-age=31536000,
      immutable'''

[[headers]]
  for = "/partial-*.html"
  [headers.values]
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/reports/*"
  [headers.values]
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=60"
    CDN-Cache-Control = "max-age=86400"

[[plugins]]
  package = "netlify-plugin-image-optim"

[[plugins]]
  package = "netlify-purge-cloudflare-on-deploy"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      ".cache", 
      "node_modules/.vite",
      "node_modules/.cache", 
    ]

[[edge_functions]]
  path = "/api/fake-edge-messages-endpoint"
  function = "fake-edge-messages-endpoint"

[[edge_functions]]
  path = "/examples/example-banner"
  function = "example-banner"

[[edge_functions]]
  path = "/*"
  function = "remove-js"

[[headers]]
  for = "/examples/example-banner"
  [headers.values]
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/blog-og-images"
  [headers.values]
    X-Robots-Tag = "noindex"

[[edge_functions]]
  path = "/og" 
  function = "og"

[[edge_functions]]
  path = "/*"
  function = "strip-non-html-headers"

[[edge_functions]]
  path = "/*"
  function = "stop-long-running-animations"

[[edge_functions]]
  path = "/*"
  function = "save-data"

[[plugins]]
  package = "netlify-plugin-inline-critical-css"
  [plugins.inputs]
    dimensions = [
      { width = 640, height = 1136 },
      { width = 768, height = 1280 },
      { width = 1024, height = 600 },
      { width = 1280, height = 800 },
      { width = 1536, height = 2048 }
    ]
    # Whether to remove the inlined styles from any stylesheet referenced in the HTML.
    # Revisit when I have more than one page. Removing the critical CSS per page results in a unique async loaded CSS file for every page, meaning you can’t rely on cache across multiple pages.
    extract = false

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    output_path = "reports/lighthouse.json"

[[edge_functions]]
  function = "webfinger"
  path = "/.well-known/webfinger"
